
export const GET_USERS = 'GET_USERS';
export const GET_USERS_SUCCEEDED = 'GET_USERS_SUCCEEDED';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';

export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_SUCCEEDED = 'CREATE_USER_SUCCEEDED';
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED';

export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCEEDED = 'DELETE_USER_SUCCEEDED';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCEEDED = 'UPDATE_USER_SUCCEEDED';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';

export const GET_SINGLE_USER = 'GET_SINGLE_USER';
export const GET_SINGLE_USER_SUCCEEDED = 'GET_SINGLE_USER_SUCCEEDED';
export const GET_SINGLE_USER_FAILED = 'GET_SINGLE_USER_FAILED';

export const LOAD_FORM = 'LOAD_FORM';
export const LOAD_FORM_SUCCEEDED = 'LOAD_FORM_SUCCEEDED';
export const LOAD_FORM_FAILED = 'LOAD_FORM_FAILED';